CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255) UNIQUE                     NOT NULL,
    chat_id     BIGINT UNIQUE                           NOT NULL,
    phone       VARCHAR(12) UNIQUE                      ,
    permissions BIGINT                                  NOT NULL,
    state_id    BIGINT,
    first_name  VARCHAR(255)                            ,
    last_name   VARCHAR(255)                            ,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS state (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value       VARCHAR(255),
    user_id     BIGINT,
    CONSTRAINT pk_state PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS masters (
    id           BIGINT NOT NULL,
    name         VARCHAR(255) UNIQUE NOT NULL,
    russian_name VARCHAR(255),
    CONSTRAINT pk_masters PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS services (
    id          BIGINT NOT NULL,
    master_id   BIGINT REFERENCES masters(id),
    name        VARCHAR(255) NOT NULL,
    CONSTRAINT pk_services PRIMARY KEY (id)
);