CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255) UNIQUE                     NOT NULL,
    chat_id     BIGINT UNIQUE                           NOT NULL,
    phone       VARCHAR(12) UNIQUE                      ,
    permissions BIGINT                                  NOT NULL,
    state_id    BIGINT,
    first_name  VARCHAR(255)                            ,
    last_name   VARCHAR(255)                            ,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS state (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value       VARCHAR(255),
    user_id     BIGINT,
    CONSTRAINT pk_state PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS recipe (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    category    VARCHAR(255),
    area        VARCHAR(255),
    ingredients VARCHAR(2048),
    measures    VARCHAR(2048),
    instruction VARCHAR(4096),
    description VARCHAR(2048),
    youtube     VARCHAR(1024),
    counter     BIGINT,
    CONSTRAINT pk_recipe PRIMARY KEY (id)
);