CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255) UNIQUE                     NOT NULL,
    chat_id     BIGINT UNIQUE                           NOT NULL,
    phone       VARCHAR(12) UNIQUE                      ,
    permissions BIGINT                                  NOT NULL,
    state_id    BIGINT,
    first_name  VARCHAR(255)                            ,
    last_name   VARCHAR(255)                            ,
    CONSTRAINT pk_users PRIMARY KEY (id)
);